<a href="https://colab.research.google.com/github/saad-aids/Data-Science-with-Saad/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hello, My Self Saad Today I am Learning Numpy,It is used for scientific computation. Its array based , In Year 2008 -2010  The Craze was Booming , Most People from  Various Countries Specially scientist were Diverting Towards the DS, But DS Was used in a Programming Langusage Called R, later when the numpy which was specially made in C language was integrated with Python Becas Python Containg List and Dictionary were Slow in the Speed Due to this Resaeon its Was Integrated With Python and Now tyou are seeing that!!This is My 13 Session On Data Science Journey

In [ ]:
import numpy as np

  1 D Array -- Vector

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


2D - Metrics

In [ ]:
b=np.array([[10,20],[30,40]])
print(b)

[[10 20]
 [30 40]]


3D - Tensor

In [ ]:
c=np.array([[10,20],[30,40],[60,70]])
print((c))

[[10 20]
 [30 40]
 [60 70]]


d type

In [ ]:
np.array([10,20,30],dtype=float)

array([10., 20., 30.])

arange its like Range Function

In [ ]:
e=np.arange(10,20)
print((e))

[10 11 12 13 14 15 16 17 18 19]


Reshape

In [ ]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

ones

In [ ]:
aa=np.ones((10,2))

In [ ]:
np.zeros((10,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

Randomn

In [ ]:
aa=np.random.random((100,10))

In [ ]:
np.size(aa)

1000

shape number of items bataata hain

In [ ]:
np.shape(aa)

(100, 10)

In [ ]:
aa.itemsize

8

In [ ]:
print(aa.dtype)

float64


Chnanging The Data type

In [ ]:
#astype resuce data type to popti
aa.dtype

dtype('float64')

To optimise when you are confidet than you will write

In [ ]:
aa.astype(np.bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

scalar -single

In [ ]:
aa*2

array([[2.58627350e-02, 1.54540933e+00, 9.06628609e-01, 7.88890932e-01,
        1.20949805e-01, 1.76993807e+00, 8.98869475e-01, 1.46211649e+00,
        1.34657066e+00, 6.18326698e-01],
       [1.32539684e+00, 1.63922705e+00, 7.45859351e-01, 2.07960308e-01,
        1.79723582e-01, 1.39057707e+00, 1.68202649e+00, 8.25515707e-01,
        1.68916489e+00, 8.75558256e-01],
       [6.49408049e-01, 1.07456083e+00, 1.80554972e+00, 8.63315523e-01,
        5.52876445e-01, 1.44250923e-01, 1.92735428e+00, 9.21105058e-01,
        1.46689001e+00, 1.00547221e+00],
       [9.56572232e-01, 1.19531374e+00, 1.63220672e+00, 8.12958574e-01,
        8.78671122e-01, 1.34100411e+00, 1.04155965e+00, 1.10995545e+00,
        1.59612272e+00, 1.97791864e+00],
       [4.95237751e-01, 1.66890911e+00, 1.31627579e+00, 1.51780655e+00,
        1.19423851e+00, 1.51380020e+00, 5.25867714e-01, 1.91694060e+00,
        1.51503737e+00, 3.57134173e-01],
       [1.49331384e+00, 2.84311694e-01, 1.37792156e+00, 1.51316987e+00,
   

In [ ]:
aa>0

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, 

Relational Operator

In [ ]:
aa==0

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

2 operatons when you do it is called as vector operations

In [ ]:
aa/aa

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 



Array Function

In [ ]:
# Dot Product (np.dot)

In [ ]:
#log and exponents (np.log)/np.exp

In [ ]:
np.random.random((2,3)*100)

In [ ]:
#round FOR ROUNDING /floor 6.9 --6/ceil  6.9--- 7

In [ ]:
#0---> ROW, 1---> COLUMN

In [ ]:
a3= np.arange(27).reshape(3,3,3)

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[2,0:2:]

array([[18, 19, 20],
       [21, 22, 23]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
a3[0,:1]

array([[0, 1, 2]])

In [ ]:
a3[0,:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a3[0,:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a3[1,:1]

array([[ 9, 10, 11]])

In [ ]:
a3[1,:2]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
a3[1,:3]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[2,:1]

In [ ]:
a3[0:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [ ]:
a3[0:3]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0:0]

array([], shape=(0, 3, 3), dtype=int64)

In [ ]:
a3[1:1]

array([], shape=(0, 3, 3), dtype=int64)

np.nditer this special code can convert any dimenisonal array

In [ ]:
a3
for i in np.nditer(a3):
 print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping
-- Reshape
-- Ravel
--Transporse (row-colum,col---row)

In [ ]:
np.transpose(a3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

kitne bhi dimension ke array ko 1 d me convert karta hai -->Ravel

In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking -- Jodna
Horizontal
Vertical

In [ ]:
a4=np.arange(1,10).reshape(3,3)
a5=np.arange(10,19).reshape(3,3)
a5

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.hstack((a4,a5))

array([[ 1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6, 16, 17, 18, 19],
       [ 7,  8,  9, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Splitting

In [ ]:
np.hsplit(a4,1)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

### Using Git in Colab

To interact with Git from Colab, you can use shell commands directly in code cells by prefixing them with an exclamation mark (`!`).

First, you'll need to configure your Git credentials (if you haven't already in this session):


In [3]:
!git config --global user.email "shaikhmsaadmsadik@gmail.com"
!git config --global user.name "saad-aids"

Then, you can use standard Git commands. For example, to check the status of a repository:


In [11]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [12]:
 !git add .

fatal: not a git repository (or any of the parent directories): .git


In [14]:
# Example: Check Git status
!git status

# Example: Add all change
!git add .

# Example: Commit changes
!git commit -m "My commit message"

# Example: Push to a remote repository (you'll likely need to clone first)
!git push origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


Remember to replace the example commands with your actual Git operations. If you need to clone a repository, you can do it like this:


In [16]:
# Example: Clone a repository
!git clone https://github.com/saad-aids/Data-Science-with-Saad.git

Cloning into 'Data-Science-with-Saad'...


In [15]:
%cd Data-Science-with-Saad

[Errno 2] No such file or directory: 'Data-Science-with-Saad'
/content


In [8]:
!git add .

fatal: not a git repository (or any of the parent directories): .git
